package:
  name: salty
  version: "1.0.0"

source:
  git_rev: "1.0.0"
  git_url: https://github.com/LanLab/SaLTy.git

requirements:
  build:
    - python
    - setuptools

  run:
    - python

test:
  imports:
    -

about:
  home: https://github.com/LanLab/SaLTy
